# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-12 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripcion', '0001_initial'),
        ('programacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='programacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programacion.Programacion'),
        ),
        migrations.AddField(
            model_name='asistenciaestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Estudiantes'),
        ),
        migrations.AddField(
            model_name='asistenciaestudiante',
            name='programacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.Programacion'),
        ),
    ]
