# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-12 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_auto_20190511_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='Ciclo_Lectivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Ciclo'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='Programa_Academico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Programa'),
        ),
    ]
